2023-07-20 11:30:08,791 - scheduler - INFO - #----------------------- Inicia proceso de Scheduler
2023-07-20 11:30:08,791 - scheduler - INFO - Orden a procesar 64b826ccafae065e70f271a2
2023-07-20 11:30:09,109 - scheduler - INFO - detener................
2023-07-20 11:30:29,110 - scheduler - INFO - continuar................
2023-07-20 11:30:29,132 - scheduler - INFO - Modulo: <module 'jobs.sendEmail.send_email' from 'd:\\WorkSpace\\WS_PERSONAL_PROGRAMS\\TaskScheduler\\backend\\jobs\\sendEmail\\send_email.py'>
2023-07-20 11:30:29,133 - scheduler - INFO - Instancia: <class 'jobs.sendEmail.send_email.SendEmail'>
2023-07-20 11:30:29,133 - scheduler - INFO - Enviar correo
2023-07-20 11:30:29,133 - scheduler - INFO - send email: smtp.googlemail.com
2023-07-20 11:30:31,098 - scheduler - INFO - Correo enviado correctamente
2023-07-20 11:30:31,099 - scheduler - INFO - Finalizo el envio
2023-07-20 11:30:31,099 - scheduler - INFO - Resultado: True
2023-07-20 11:30:31,129 - scheduler - INFO - Scheduler finalizado con exito
2023-07-20 11:30:31,134 - scheduler - INFO - Proceso termino exitosamente.
2023-07-20 11:30:31,137 - scheduler - ERROR - Error.........................: 'SchedulerService' object has no attribute 'collection'
Traceback (most recent call last):
  File "d:\WorkSpace\WS_PERSONAL_PROGRAMS\TaskScheduler\backend\routes\chains_routes.py", line 132, in process
    process_record(spooler.logger, values, "SUCCESS")
  File "d:\WorkSpace\WS_PERSONAL_PROGRAMS\TaskScheduler\backend\routes\chains_routes.py", line 157, in process_record
    scheduler_service.update_historical(values)
  File "d:\WorkSpace\WS_PERSONAL_PROGRAMS\TaskScheduler\backend\services\process\scheduler_service.py", line 31, in update_historical
    self.collection.update_one(filter, {"$set": data})
    ^^^^^^^^^^^^^^^
AttributeError: 'SchedulerService' object has no attribute 'collection'

2023-07-20 11:30:31,138 - scheduler - INFO - Proceso termino con error.
